### PR TITLE
Require PkgConfig if you need to use it

### PR DESCRIPTION
**Pull request by agravgaard**
Because I suddenly got the following error in my CI:
`CMake Error at build/DCMTK-src/CMake/FindOpenJPEG.cmake:10 (pkg_check_modules):`
`  Unknown CMake command "pkg_check_modules".`
`Call Stack (most recent call first):`
`  build/DCMTK-src/CMake/3rdparty.cmake:340 (find_package)`
`  build/DCMTK-src/CMake/dcmtkPrepare.cmake:429 (include)`
`  build/DCMTK-src/CMakeLists.txt:17 (include)`

### CODE REVIEW

**Comment by jriesmeier** [comment]
Thank you for the patch. Wouldn't it make more sense to replace "REQUIRED" with "QUIET"? Otherwise the entire configure process will fail if the CMake module "PkgConfig" is missing on the system.

CC: @eichelberg

**Comment by jriesmeier** [comment]
Fixed with commit 82fb238.

**Comment by agravgaard** [comment]
Sure, that's fine with me. But "Unknown CMake command" is also an error, so I think it would halt anyway in that case.

Thanks!

**Comment by jriesmeier** [comment]
Right, therefore my committed patch looks like this:

```
diff --git a/CMake/FindOpenJPEG.cmake b/CMake/FindOpenJPEG.cmake
index 69617c6..8589edc 100644
--- a/CMake/FindOpenJPEG.cmake
+++ b/CMake/FindOpenJPEG.cmake
@@ -7,7 +7,10 @@
 #  OPENJPEG_FOUND        - True if OpenJPEG found
 
 # Use pkg_check_modules to determine the paths for OpenJPEG
-pkg_check_modules(OPENJPEG_PKGCONF libopenjp2)
+find_package(PkgConfig QUIET)
+if(PKG_CONFIG_FOUND)
+  pkg_check_modules(OPENJPEG_PKGCONF libopenjp2)
+endif()
 
 # Look for the header file
 find_path(OPENJPEG_INCLUDE_DIR NAMES openjpeg.h HINTS ${OPENJPEG_PKGCONF_INCLUDE_DIRS})

```

**Comment by agravgaard** [comment]
Great, much better!

**Comment by jriesmeier** [comment]
The new version will be visible on GitHub soon (still have to wait for the nightly builds).

**Pull request closed without merging**
