### PR TITLE
Add Transport Layer Security functionality to DcmSCP and DcmSCPPool

### PR DESCRIPTION
**Pull request by amatm**
Agregate a Transport Layer Security pointer to DcmSCPConfig.
Update classes DcmSCP and DcmSCPPool to use it.
Add tests in dcmtls for checking scp+tls and poolScp+tls.

Authors:  Michel Amat, Damien Lerat

### CODE REVIEW

**Comment by amatm** [comment]
Hi,
at the moment, the Transport Layer Security functionality for DcmSCPPool class is not provided by dcmtk, as confirmed in the dcmtk's forum at topic: https://forum.dcmtk.org/viewtopic.php?f=1&t=4786
We implemented it and would be happy to see it integrated in the official repository.
Cheers,
Michel Amat, Damien Lerat

**Comment by offis-jas** [comment]
I just read the title of the patch, if this does what you claim, this would be
awesome, we would definitely want to integrate this.
I've added it on my ToDo list to look at the actual code and (hopefully)
accept this patch into DCMTK ASAP, not sure when I'll actually get to it
though, so, if a colleague can be faster, don't hold back.

**Comment by amatm** [comment]
Force-pushed to remove in dcmtls/tests/tscuscptls.cc use of function setCipherSuites,
that is not present anymore in 3.6.4.
Sorry for that.

**Comment by eichelberg** [comment]
The pull request has been merged into the testing branch of our internal git repository today. The update should be mirrored to the public git here in a couple of days. Thank you very much for your contribution!

**Comment by mamat-corp** [comment]
Ok, great.
You're welcome!

**Pull request closed without merging**
