### PR TITLE
fixes for poll use

### PR DESCRIPTION
**Pull request by sercxjo**
The patch fixes errors with network connection after commit 5fae4f233a41232bca18595dd8b5c2515617855f under Linux.

### CODE REVIEW

**Comment by PavelTrushkin** [comment]
grrr, i spent 4 hours catching POLLOUT...

**Comment by michaelonken** [comment]
@sercxjo Thanks for the report, do you have a test program that demonstrates the issue? Switching to POLLOUT when requesting an association sounds logical to me, but DCMTK network tests surprisingly still work on my linux box without applying your patch.

**Comment by PavelTrushkin** [comment]
Michael, yes it works LOCALLY but will fail if  connect return EINPROGRESS 

Please check man poll there is explicitly required pillout after connect

**Comment by PavelTrushkin** [comment]
In other words if you call poll(POLLIN) after connect/EINPROGRESS you will get timeout, I can reproduce it 100%

**Comment by sercxjo** [comment]
We use different PACS servers (Orthanc and other) in other buildings with internet connection and our program based on modified storescp/storescu. Set all timeouts to 60s. All worked before 5fae4f233a41232bca18595dd8b5c2515617855f

**Comment by michaelonken** [comment]
I looked it up on the connect() man page, and took over the POLLOUT versus the POLLIN. It will show up on DCMTK master during the next day. Thanks Sergej!

I'm now looking at the rest of your patch ;)

**Comment by michaelonken** [comment]
Sergej, the POLLIN/POLLOUT part of the [patch is in DCMTK now for some time](http://git.dcmtk.org/?p=dcmtk.git;a=commit;h=0630c52fff6d0422a7aeadde521133fa888bf57f).

What does the rest of the patch do, i.e. the changes to dcmnet/libsrc/dcmtrans.cc?

**Comment by eichelberg** [comment]
This patch has now been fully merged into DCMTK with commit #73107ff (2018-06-12).
Note that the patch contained one bug which has been fixed in the commit: The second poll() parameter must be "pfd.size()" and not "connCount".

**Comment by michaelonken** [comment]
Thanks for taking care of this Marco

**Comment by sercxjo** [comment]
Thanks

**Comment by PavelTrushkin** [comment]
could you push commit 73107ff ? i don't see it.

**Comment by michaelonken** [comment]
Just did that (every commit goes through a testing dashboard, that's why it can take a few days until we push it to the public branches).

**Pull request closed without merging**
