### PR TITLE
Img2dcm jpegls refactor

### PR DESCRIPTION
**Pull request by malaterre**

### CODE REVIEW

**Comment by malaterre** [comment]
@michaelonken This PR should be a bit more user-friendly, since one can now simply:

`$ img2dcm input.jpg output.dcm`

There is no need to state in advanced that the JPEG bitstream is JPEG-LS explicitly.

**Comment by michaelonken** [comment]
P.S: In any case this will go into DCMTK upstream after the next release, i.e. probably next month.

**Comment by malaterre** [comment]
@michaelonken I've update the man page see commit 5feea373c05adb28419fafe4b5bb249f6f2755f6. While doing so I discover I missed one handling (APP8 + HP color transform of none), see 8168f6a40e9bfbd2c98058800db9fc81d5845187.

Thanks

**Comment by malaterre** [comment]
> P.S: In any case this will go into DCMTK upstream after the next release, i.e. probably next month.

any update ? thanks !

**Comment by michaelonken** [comment]
Hi, yeah, it got a bit late... it's still on my list though, sorry for the waiting time Mathieu.

**Pull request closed without merging**
